### ISSUE TITLE
sbt-multi-jvm doesn't clean up target/multi-run-copied-libraries which will lead to strange classpaths after dependency updates

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt-multi-jvm#32] opened 2017-06-28 14:16 UTC

**Comment by dwijnand** [comment] 2019-10-24 10:21
This is bad.  I almost feel like it should be documented in the README until it's fixed.  WDYT?

**Comment by johanandren** [comment] 2019-10-31 08:34
I wonder if this is the same as #18

**Comment by dwijnand** [comment] 2019-10-31 13:08
Yeah, looks like it.

**Comment by dwijnand** [comment] 2019-10-31 13:08
Duplicate of #18

**Closed by dwijnand** 2019-10-31 13:08 UTC
Labels: bug
